version: '3.8'

services:
  app:
    build: .
    container_name: nest-task-app
    ports:
      - "3000:3000"    # Expose the app on port 3000
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo/nest-task-management
     # Connect to the MongoDB container
    networks:
      - app-net

  mongo:
    image: mongo:6          # Use the official MongoDB image
    container_name: mongo
    ports:
      - "27017:27017"       # Expose MongoDB on the host machine's port 27017
    volumes:
      - mongo-data:/data/db  # Persist data between container restarts
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net: {}  # Define the network explicitly
