global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'nestjs_app'
    static_configs:
      - targets: ['nestapp:3000']  # The service name of your app in Docker Compose
