name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract version from package.json
      id: get_version
      run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

    - name: Show version
      run: echo "Building image with version $VERSION"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nest-task-manager:$VERSION
